alter account a drop old url;
alter api integration ai set enabled = false;
alter connection c primary;
alter database d RENAME TO d2;
alter external table et refresh;
alter failover group fg rename to fg2;
alter file format ff RENAME TO ff2;
alter function f() RENAME TO f2;
alter masking policy mp rename to mp2;
alter materialized view mv rename to mv2;
alter network policy np rename to np2;
alter notification integration ni set enabled = false notification_provider = gcp_pubsub gcp_pubsub_subscription_name = '';
alter pipe p REFRESH;
alter procedure pr() RENAME TO p2;
alter resource monitor rm set credit_quota = 1;
alter role r RENAME TO r2;
alter row access policy rap rename to rap2;
alter schema sch rename to sch2;
alter sequence seq rename to seq2;
alter session set autocommit = true;
alter table t rename to t2;
alter tag tg rename to tg2;
alter user u reset password;
alter view vw set secure;
alter warehouse wh suspend;
alter sequence seq set ORDER COMMENT ='A comment';
alter sequence seq set NOORDER;
ALTER ALERT my_alert SET SCHEDULE = '2 minutes';
ALTER ALERT my_alert MODIFY CONDITION EXISTS (SELECT gauge_value FROM gauge WHERE gauge_value>300);
ALTER ALERT myalert RESUME;
ALTER ALERT my_alert SET WAREHOUSE = my_other_warehouse;