copy into t from @stage/;
copy into @stage/ from t;
commit ;
execute immediate 'select 1';
execute task tsk;
explain select 1 as c;
get @stage/ file:///tmp/load;
list @stage/;
put file:///tmp/load @stage;
remove @stage/;
revoke role r from role t1;
rollback;
set i=1;
truncate materialized view v;
truncate table t;
unset i;
unset (i,j,k);
get @stage/ file://C:\temp\load;
put file://C:\temp\load @stage;